### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by kisaapear** [ethaniccc/KitGUI#2]
I can help you with this via discord

**Comment by ethaniccc** [comment]
How can you help, and what is your discord?

**Comment by kisaapear** [comment]
> How can you help, and what is your discord?

give me your discord i'll add u

**Comment by ethaniccc** [comment]
TheSacrafice#5034 ( i think)

**Comment by ethaniccc** [comment]
I have figured out the fix, thank you for your attempt though! :D
